### ISSUE TITLE
refactor : nickname이 user의 nickname인 경우 PRIVATE 카테고리 조회 가능 / user entity의 publishCategory를 통해 공개 여부 조정

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#104]
### ⚠️ Issue
- 카테고리 조회 시 받아온 nickname이 본인의 nickname인 경우 PRIVATE이여도 조회 가능하게 구현
   - 기본적으로 내 카테고리 조회는 PUBLIC / PRIVATE 모두 조회 가능
- 각 카테고리에 대한 publish 여부가 아닌 user entity의 publishCategory에 따라 공개 여부 처리

### ✅ Todo
- [x] nickname이 user의 nickname인 경우 PRIVATE 카테고리 조회
- [x] user entity의 publishCategory를 통해 공개 여부 조정
- [x] user error code 404101 중복 해결 

### 🔗RelatedTo
- #7 #18
