### ISSUE TITLE
refactor: api명칭, dto형식/ PublishRoute 필드 반영

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#116]
### ⚠️ Issue
refactor: Route와 RouteList API Controller 통일/DTO 구조 리팩토링
feat: PublishRoute 필드 추가

### ✅ Todo
- [ ]  Route와 RouteList API Controller 통일
- [x] general예외를 상속으로 통일
- [x] PublishRoute 필드 반영
- [x] DTO 이너클래스 해제

### 🔗RelatedTo
- 관련이 있는 issue가 있다면 링크 시켜주세요
