### ISSUE TITLE
refactor : 카테고리 조회 시 설명 부분 추가 조회 / fix : 카테고리 수정 시 중복이름 버그 수정

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#139]
### ⚠️ Issue
- 카테고리 전체 조회 시 myCategoryScript를 포함해 조회될 수 있도록 수정
- 카테고리 수정 시 이름이 아닌 다른 필드 수정할 경우 중복이름 버그 수정

### ✅ Todo
- [x] 카테고리 전체 조회 시 myCategoryScript 추가 조회
- [x] 위치 기반 카테고리 전체 조회 시 myCategoryScript 추가 조회
- [x] 카테고리 이름 중복 처리 시 현재 수정하고 있는 카테고리에 대해서은 중복 처리 금지

### 🔗RelatedTo
- #7, #18
