### ISSUE TITLE
refactor: 리뷰의 이미지를 넘기는 API들 중에서 리뷰 대표 이미지만 넘기면 되는 API의 응답값 수정

### ISSUE THREAD

**Issue by yujiyea** [gusto-umc/Gusto-Server#152]
### ⚠️ Issue
리뷰의 이미지를 넘기는 API들은 리뷰의 모든 이미지를 response에 담았습니다.
하지만, 인스타뷰, 캘린더뷰, 타인 리뷰 모아보기, 먹스또 랜덤 피드는 대표 이미지 한 개만 필요합니다.
이미지 한 개만 넘기도록 수정 필요

### ✅ Todo
- [ ] 리뷰 모아보기 - 인스타뷰 API
- [ ] 리뷰 모아보기 - 캘린더뷰 API
- [ ] 타인 리뷰 모아보기
- [ ] 먹스또 랜덤 피드

### 🔗RelatedTo
#73, #76, #95
