### ISSUE TITLE
refactor : 리뷰 조회 시 status을 거치도록 수정 / 방문 날짜를 기준으로 리뷰 조회

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#184]
### ⚠️ Issue
- 리뷰 조회 시 status가 ACTIVE인지 확인하고 처리한다.
- 방문 날짜를 기준으로 리뷰를 조회한다

### ✅ Todo
- [x] 리뷰 조회 시 status가 ACTIVE인지 쿼리로 처리하기
- [x] 방문 날짜를 기준으로 리뷰 조회하기
- [x] 리뷰 페이징 처리 시 visitedAt를 추가로 받기
