### ISSUE TITLE
feat: 닉네임 중복 체크

### ISSUE THREAD

**Issue by zzo3ozz** [gusto-umc/Gusto-Server#22]
### ⚠️ Issue
- 닉네임 중복 체크

### ✅ Todo
- [x] social 로그인 시 체크
- [x] 회원가입 api 시 체크
- [x] 중복 체크 자체 api

### 🔗RelatedTo
- #11 #10
