### ISSUE TITLE
feat: 페이징 작업: 루트,그룹

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#231]
### ⚠️ Issue
- 데모데이 이후 페이징 작업을 진행합니다.

### ✅ Todo
- [x] 그룹 내 가게 목록: 처음 8개, 페이징 6개씩 추가
- [x] 그룹 내 루트: 처음 6개, 페이징 6개씩 추가
- [x] 내 루트 목록 조회: 처음 6개, 페이징 6개씩 추가
- [x] 타인의 루트 목록 조회: 처음 6개, 페이징 6개씩 추가

### 🔗RelatedTo
- 관련이 있는 issue가 있다면 링크 시켜주세요
