### ISSUE TITLE
refactor : MyCategory entity / null 처리를 위한 방법 수정 / PRIVATE 경우 카테고리 조회 불가

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#26]
### ⚠️ Issue
- @Builder.Default 공통 처리 & MyCategory Entity Status 필드 삭제 / @Setter 추가
- isPresent 대신  .orElseThrow()로 null 처리
- 각 클래스 Optional로 처리

### ✅ Todo
- [x] entity 관련 수정사항
- [x] isPresent 메서드를 사용하는 대신 .orElseThrow() 사용
- [x] Optional 클래스 사용
- [x] 내 카테고리가 private일 경우 조회 불가 처리

### 🔗RelatedTo
- #17 에서 수정 후 pr을 날리려고 했으나 새롭게 refactor를 하는게 좋을 거 같아 새로 이슈를 작성합니다.
