### ISSUE TITLE
feat : 내 카테고리 개별/전체 공개 여부에 따른 수정 및 추가

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#275]
### ⚠️ Issue
- User의 publishCategory가 PUBLIC일 경우에만 MyCategory의 publishCategory를 수정
- User의 publishCategory가 PRIVATE이 되는 순간, 원래의 MyCategory의 publishCategory 값을 기억
- 타인의 카테고리 조회 시 User의 publishCategory 조회 시 null 처리

### ✅ Todo
- [x] 이전 publishCategory를 저장하는 previousPublishCategory 추가
- [x] publishCategory에 따른 쿼리문 수정
- [x] User의 publishCategory에 따라 변경되는 savePublishCategory 메서드 추가
- [x] User의 publishCategory가 PRIVATE일 때 update 못하게 USER_PUBLISH_CATEGORY_PRIVATE 에러 처리
