### ISSUE TITLE
feat: 루트 공개/비공개 여부

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#282]
### ⚠️ Issue
- 마이페이지 내에서 공개/비공개 여부를 루트에서 반영받음
- 각 루트의 생성시, 조회 시 공개여부 변경 가능

### ✅ Todo
- [x] 루트 생성 시 공개/비공개 필드 추가
- [x] 수정작업- 타인의 루트 조회 시 공개된 루트 한정 조건 추가
- [x] 루트 목록 페이지에서 공개/비공개 변경 API 추가

### 🔗RelatedTo
- #188
