### ISSUE TITLE
refactor : 내 카테고리는 private 값이여도 확인 가능하게 수정

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#293]
### ⚠️ Issue
- 내 카테고리 조회 시 PRIVATE이면 안보이는 경우

### ✅ Todo
- [x] PRIVATE일때도 나의 카테고리 조회 되도록 수정
- [x] 카테고리 조회 시 img 3개 response 처리
- [x] 이미지가 null 일때 ""처리

### 🔗RelatedTo
- #275
