### ISSUE TITLE
refactor : 토큰 반환이 필요 없는 API 토큰 삭제 처리

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#300]
### ⚠️ Issue
- 가게 조회 시 리뷰 조회 과정에서 토큰 사용 삭제
- 타인의 카테고리 조회 과정에서 토큰 사용 삭제

### ✅ Todo
- [x] 타인의 카테고리 조회 시 토큰 처리 삭제
- [x] 가게 조회 시 본인 PRIVATE 리뷰 확인을 위해 사용하던 토큰 반환 삭제
- [x] 가게 조회 시 토큰 여부에 따라 찜 여부 반환

### 🔗RelatedTo
- #7 
- #71
