### ISSUE TITLE
refactor: 전체 리펙토링 리스트

### ISSUE THREAD

**Issue by zzo3ozz** [gusto-umc/Gusto-Server#45]
### ⚠️ Issue
- 공통적으로 체크해야 할 리펙토링 리스트 입니다.

### ✅ Todo
- [ ] Exception 처리 (에러 핸들러 작업에 맞춰서)
- [ ] Service단의 `@Trasactional`, `@Transactional(readOnly = true)` 처리
- [ ] Resource 생성 시 `HttpStatus.CREATED`로 리턴
