### ISSUE TITLE
refactor: Route Status가 고려, Soft Delete로 변경

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#47]
### ⚠️ Issue
- Route 리팩토링 작업 진행

### ✅ Todo
- [x] 전체 리팩토링 코드 반영
- [x] Route Status가 고려 후 ACTIVE 조회
- [x] soft Delete로 삭제 코드 리팩토링

### 🔗RelatedTo
- #45
