### ISSUE TITLE
feat : 엔티티 생성 (MyCategory, Review, User)

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#5]
### ⚠️ Issue
- 엔티티 생성(myCategory, user, review)

### ✅ Todo
- [x] MyCategory, Pin Entity
- [x] Review, Liked, Tagging, HashTag Entity
- [x] User, Follow, Social Entity
- [x] 양방향 연결
