### ISSUE TITLE
refactor: S3 단일 이미지, 다수 이미지 로직 분리

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#53]
### ⚠️ Issue
- S3 리팩토링 작업 진행

### ✅ Todo
- [x] 버킷에서 png, jpg,gif,jpeg 등 이미지 파일만 저장되도록 정책 수정
- [x] refactor: 이미지 저장 로직 분리(단일,다수) 
- [x] 원활한 테스트를 위해 삭제 Controller추가

### 🔗RelatedTo
- 관련이 있는 issue가 있다면 링크 시켜주세요.
- #39
