### ISSUE TITLE
refactor: Group CRUD 관련 리펙토링

### ISSUE THREAD

**Issue by Jeonghee-Han** [gusto-umc/Gusto-Server#57]
### ⚠️ Issue
- Group CRUD 리펙토링 작업

### ✅ Todo
- [x] 예외 처리
- [x] 그룹 삭제 시 그룹의 식당 리스트, 루트 리스트 삭제
- [x] Resource 생성 시 HttpStatus.CREATED로 리턴
- [x] Group request, response 이너 클래스 대신 각 클래스로 수정

### 🔗RelatedTo
#45
