### ISSUE TITLE
refactor: UserService단의 Exception 변경, CountBy -> ExistsBy

### ISSUE THREAD

**Issue by zzo3ozz** [gusto-umc/Gusto-Server#58]
### ⚠️ Issue
- UserService단의 남아 있는 RuntimeException 변경
- GeneralException 처리한 내용을 NotFoundException 등의 CustomException으로 변경
- 중복 확인 시 CountBy가 아닌 ExistsBy 사용

### ✅ Todo
- [ ] UserService단의 남아 있는 RuntimeException 변경
- [ ] GeneralException 처리한 내용을 NotFoundException 등의 CustomException으로 변경
- [ ] 중복 확인 시 CountBy가 아닌 ExistsBy 사용

### 🔗RelatedTo
- #48 review
