### ISSUE TITLE
feat : 가게를 특정 카테고리에 찜 / 찜 취소 API

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#66]
### ⚠️ Issue
- 가게를 특정 카테고리에 찜하고 취소하는 기능 구현

### ✅ Todo
- [x] 가게를 특정 카테고리에 찜 API
- [x] 가게를 특정 카테고리에서 삭제 API (Hard delete로 구현)
    - [x] 다중 삭제 가능하게 처리
