### ISSUE TITLE
refactor : MyCategory CRUD 공통 리펙토리

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#67]
### ⚠️ Issue
- MyCategory CRUD

### ✅ Todo
- [x] Exception 처리
- [x] @Transactional 처리 추가
- [x] HttpStatus.CREATED 처리
- [x] soft delete를 위한 patchingMapping을 deleteMapping으로 변경

### 🔗RelatedTo
#7 #18
