### ISSUE TITLE
feat : 내 카테고리 CRUD API 작성

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#7]
### ⚠️ Issue
- 내 카테고리 CRUD API 작성하기

### ✅ Todo
- [x] 내 카테고리 조회 GET
- [x] 내 카테고리 생성 POST
- [x] 내 카테고리 수정 PATCH
- [x] 내 카테고리 삭제 DELETE
