### ISSUE TITLE
feat : 가게 정보 조회 API

### ISSUE THREAD

**Issue by kchaeeun** [gusto-umc/Gusto-Server#71]
### ⚠️ Issue
- 가게 정보 조회 API 구현

### ✅ Todo
- [x] 가게 정보 조회 API
- [x] 가게 상세 정보 조회 API
    - [x] 리뷰 페이징 처리
