### ISSUE TITLE
feat: 그룹 내 식당 API

### ISSUE THREAD

**Issue by Hwater00** [gusto-umc/Gusto-Server#88]
### ⚠️ Issue
- 그룹 내 식당 관련 API입니다. 식당 추가, 삭제, 수정 
- 그룹 구성원이 식당을 찜하면 그룹 내 식당이 추가, 그룹 구성원 모두 삭제 가능

### ✅ Todo
- [x] 그룹 내 식당 추가
- [x] 그룹 내 식당 삭제
- [x] 그룹 내 식당 목록 

### 🔗RelatedTo
- 관련이 있는 issue가 있다면 링크 시켜주세요
